// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserManagement.Data;

#nullable disable

namespace UserManagement.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserManagement.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Forename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DateOfBirth = new DateOnly(1955, 3, 22),
                            Email = "ploew@example.com",
                            Forename = "Peter",
                            IsActive = true,
                            Surname = "Loew"
                        },
                        new
                        {
                            Id = 2L,
                            DateOfBirth = new DateOnly(1968, 7, 15),
                            Email = "bfgates@example.com",
                            Forename = "Benjamin Franklin",
                            IsActive = true,
                            Surname = "Gates"
                        },
                        new
                        {
                            Id = 3L,
                            DateOfBirth = new DateOnly(1970, 11, 2),
                            Email = "ctroy@example.com",
                            Forename = "Castor",
                            IsActive = false,
                            Surname = "Troy"
                        },
                        new
                        {
                            Id = 4L,
                            DateOfBirth = new DateOnly(1965, 5, 30),
                            Email = "mraines@example.com",
                            Forename = "Memphis",
                            IsActive = true,
                            Surname = "Raines"
                        },
                        new
                        {
                            Id = 5L,
                            DateOfBirth = new DateOnly(1972, 9, 18),
                            Email = "sgodspeed@example.com",
                            Forename = "Stanley",
                            IsActive = true,
                            Surname = "Goodspeed"
                        },
                        new
                        {
                            Id = 6L,
                            DateOfBirth = new DateOnly(1958, 2, 10),
                            Email = "himcdunnough@example.com",
                            Forename = "H.I.",
                            IsActive = true,
                            Surname = "McDunnough"
                        },
                        new
                        {
                            Id = 7L,
                            DateOfBirth = new DateOnly(1975, 4, 5),
                            Email = "cpoe@example.com",
                            Forename = "Cameron",
                            IsActive = false,
                            Surname = "Poe"
                        },
                        new
                        {
                            Id = 8L,
                            DateOfBirth = new DateOnly(1969, 12, 25),
                            Email = "emalus@example.com",
                            Forename = "Edward",
                            IsActive = false,
                            Surname = "Malus"
                        },
                        new
                        {
                            Id = 9L,
                            DateOfBirth = new DateOnly(1960, 8, 14),
                            Email = "dmacready@example.com",
                            Forename = "Damon",
                            IsActive = false,
                            Surname = "Macready"
                        },
                        new
                        {
                            Id = 10L,
                            DateOfBirth = new DateOnly(1980, 6, 21),
                            Email = "jblaze@example.com",
                            Forename = "Johnny",
                            IsActive = true,
                            Surname = "Blaze"
                        },
                        new
                        {
                            Id = 11L,
                            DateOfBirth = new DateOnly(1963, 1, 9),
                            Email = "rfeld@example.com",
                            Forename = "Robin",
                            IsActive = true,
                            Surname = "Feld"
                        });
                });

            modelBuilder.Entity("UserManagement.Models.UserLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("AfterJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("UserLogs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Action = 0,
                            AfterJson = "{\"Id\":1,\"Forename\":\"Peter\",\"Surname\":\"Loew\",\"Email\":\"ploew@example.com\",\"IsActive\":true,\"DateOfBirth\":\"1955-03-22\"}",
                            Timestamp = new DateTime(2026, 9, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Action = 0,
                            AfterJson = "{\"Id\":2,\"Forename\":\"Benjamin Franklin\",\"Surname\":\"Gates\",\"Email\":\"bfgates@example.com\",\"IsActive\":true,\"DateOfBirth\":\"1968-07-15\"}",
                            Timestamp = new DateTime(2026, 9, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            Action = 0,
                            AfterJson = "{\"Id\":3,\"Forename\":\"Castor\",\"Surname\":\"Troy\",\"Email\":\"ctroy@example.com\",\"IsActive\":false,\"DateOfBirth\":\"1970-11-02\"}",
                            Timestamp = new DateTime(2026, 9, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            Action = 0,
                            AfterJson = "{\"Id\":4,\"Forename\":\"Memphis\",\"Surname\":\"Raines\",\"Email\":\"mraines@example.com\",\"IsActive\":true,\"DateOfBirth\":\"1965-05-30\"}",
                            Timestamp = new DateTime(2026, 9, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 4L
                        },
                        new
                        {
                            Id = 5L,
                            Action = 0,
                            AfterJson = "{\"Id\":5,\"Forename\":\"Stanley\",\"Surname\":\"Goodspeed\",\"Email\":\"sgodspeed@example.com\",\"IsActive\":true,\"DateOfBirth\":\"1972-09-18\"}",
                            Timestamp = new DateTime(2026, 9, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 5L
                        },
                        new
                        {
                            Id = 6L,
                            Action = 0,
                            AfterJson = "{\"Id\":6,\"Forename\":\"H.I.\",\"Surname\":\"McDunnough\",\"Email\":\"himcdunnough@example.com\",\"IsActive\":true,\"DateOfBirth\":\"1958-02-10\"}",
                            Timestamp = new DateTime(2026, 9, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 6L
                        },
                        new
                        {
                            Id = 7L,
                            Action = 0,
                            AfterJson = "{\"Id\":7,\"Forename\":\"Cameron\",\"Surname\":\"Poe\",\"Email\":\"cpoe@example.com\",\"IsActive\":false,\"DateOfBirth\":\"1975-04-05\"}",
                            Timestamp = new DateTime(2026, 9, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 7L
                        },
                        new
                        {
                            Id = 8L,
                            Action = 0,
                            AfterJson = "{\"Id\":8,\"Forename\":\"Edward\",\"Surname\":\"Malus\",\"Email\":\"emalus@example.com\",\"IsActive\":false,\"DateOfBirth\":\"1969-12-25\"}",
                            Timestamp = new DateTime(2026, 9, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 8L
                        },
                        new
                        {
                            Id = 9L,
                            Action = 0,
                            AfterJson = "{\"Id\":9,\"Forename\":\"Damon\",\"Surname\":\"Macready\",\"Email\":\"dmacready@example.com\",\"IsActive\":false,\"DateOfBirth\":\"1960-08-14\"}",
                            Timestamp = new DateTime(2026, 9, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 9L
                        },
                        new
                        {
                            Id = 10L,
                            Action = 0,
                            AfterJson = "{\"Id\":10,\"Forename\":\"Johnny\",\"Surname\":\"Blaze\",\"Email\":\"jblaze@example.com\",\"IsActive\":true,\"DateOfBirth\":\"1980-06-21\"}",
                            Timestamp = new DateTime(2026, 9, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 10L
                        },
                        new
                        {
                            Id = 11L,
                            Action = 0,
                            AfterJson = "{\"Id\":11,\"Forename\":\"Robin\",\"Surname\":\"Feld\",\"Email\":\"rfeld@example.com\",\"IsActive\":true,\"DateOfBirth\":\"1963-01-09\"}",
                            Timestamp = new DateTime(2026, 9, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 11L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
